describe('SauceDemo',()=>{
beforeEach(()=>{
cy.visit('/')
cy.fixture('user').as('user')
})
it('Compra',function(){
cy.login()
cy.url().should('include','inventory')
cy.screenshot('login')
cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
cy.get('.shopping_cart_link').click()
cy.contains('Sauce Labs Backpack')
cy.contains('Sauce Labs Bike Light')
cy.get('[data-test="checkout"]').click()
cy.get('[data-test="firstName"]').type(this.user.firstName)
cy.get('[data-test="lastName"]').type(this.user.lastName)
cy.get('[data-test="postalCode"]').type(this.user.postalCode)
cy.get('[data-test="continue"]').click()
cy.contains('Payment Information')
cy.get('[data-test="finish"]').click()
cy.contains('THANK YOU FOR YOUR ORDER').should('be.visible')
cy.screenshot('success')
})
})